// Prompt question IDs and text mapping
// This file is auto-generated for use in tests and other modules

export const PROMPT_QUESTIONS = [
  {
    id: "cmjrkgtpe0000dxgdrajkb8zl",
    question: "Two truths and a lie — go.",
    category: "FUN",
    enabled: true,
    order: 1,
  },
  {
    id: "cmjrkgtpe0001dxgdaalc9wp1",
    question: "The most spontaneous thing I've ever done is…",
    category: "FUN",
    enabled: true,
    order: 2,
  },
  {
    id: "cmjrkgtpe0002dxgdj5az1ut6",
    question: "My most irrational fear is…",
    category: "FUN",
    enabled: true,
    order: 3,
  },
  {
    id: "cmjrkgtpe0003dxgd5izbl0d8",
    question: "I'm weirdly competitive about…",
    category: "FUN",
    enabled: true,
    order: 4,
  },
  {
    id: "cmjrkgtpe0004dxgd13hwv8vj",
    question: "The last thing that made me laugh way too hard was…",
    category: "FUN",
    enabled: true,
    order: 5,
  },
  {
    id: "cmjrkgtpe0005dxgdj48aludl",
    question: "A perfect Sunday for me looks like…",
    category: "ICEBREAKER",
    enabled: true,
    order: 6,
  },
  {
    id: "cmjrkgtpe0006dxgdhgr7gii0",
    question: "I'll fall for you if…",
    category: "ICEBREAKER",
    enabled: true,
    order: 7,
  },
  {
    id: "cmjrkgtpe0007dxgd8asbhu0g",
    question: "The quickest way to my heart is…",
    category: "ICEBREAKER",
    enabled: true,
    order: 8,
  },
  {
    id: "cmjrkgtpe0008dxgd00g7i3l4",
    question: "The best first message I've ever received was…",
    category: "ICEBREAKER",
    enabled: true,
    order: 9,
  },
  {
    id: "cmjrkgtpe0009dxgd267l0mni",
    question: "One thing you should know about me is…",
    category: "ICEBREAKER",
    enabled: true,
    order: 10,
  },
  {
    id: "cmjrkgtpe000adxgdc2damwt9",
    question: "My ideal way to unwind after a long day is…",
    category: "LIFESTYLE",
    enabled: true,
    order: 11,
  },
  {
    id: "cmjrkgtpe000bdxgdku6w12gs",
    question: "A habit I'm trying to build right now is…",
    category: "LIFESTYLE",
    enabled: true,
    order: 12,
  },
  {
    id: "cmjrkgtpe000cdxgdhn3lgz4u",
    question: "My relationship with my phone is best described as…",
    category: "LIFESTYLE",
    enabled: true,
    order: 13,
  },
  {
    id: "cmjrkgtpe000ddxgdsnj6migx",
    question: "If we were stranded on an island, I'd be responsible for…",
    category: "LIFESTYLE",
    enabled: true,
    order: 14,
  },
  {
    id: "cmjrkgtpe000edxgdkphyr1t9",
    question: "My go-to comfort activity is…",
    category: "LIFESTYLE",
    enabled: true,
    order: 15,
  },
  {
    id: "cmjrkgtpe000fdxgd86dcnc6e",
    question: "A value I won't compromise on is…",
    category: "VALUES",
    enabled: true,
    order: 16,
  },
  {
    id: "cmjrkgtpe000gdxgdkdnxolge",
    question: "A green flag I look for in people is…",
    category: "VALUES",
    enabled: true,
    order: 17,
  },
  {
    id: "cmjrkgtpe000hdxgd6rjsia3s",
    question: "Something I'm genuinely grateful for is…",
    category: "VALUES",
    enabled: true,
    order: 18,
  },
  {
    id: "cmjrkgtpe000idxgdy3bphhu9",
    question: "The hallmark of a healthy relationship is…",
    category: "VALUES",
    enabled: true,
    order: 19,
  },
  {
    id: "cmjrkgtpe000jdxgd1oqgp95z",
    question: "Something I'm currently working on about myself is…",
    category: "VALUES",
    enabled: true,
    order: 20,
  },
];

// Answer mapping for each prompt question
export const PROMPT_ANSWERS = {
  cmjrkgtpe0000dxgdrajkb8zl: ["Being more patient."],
  cmjrkgtpe0001dxgdaalc9wp1: ["Booked a flight to a random country on a whim!"],
  cmjrkgtpe0002dxgdj5az1ut6: ["Elevators. I always think they'll get stuck."],
  cmjrkgtpe0003dxgd5izbl0d8: [
    "Board games. I have to win!",
    "Trivia nights with friends.",
    "Running races, even against myself.",
  ],
  cmjrkgtpe0004dxgd13hwv8vj: [
    "A friend's joke during dinner—couldn't stop laughing!",
  ],
  cmjrkgtpe0005dxgdj48aludl: [
    "Sleeping in, brunch, and a walk in the park.",
    "Yoga and a good book.",
    "Cooking a new recipe and relaxing.",
  ],
  cmjrkgtpe0006dxgdhgr7gii0: ["If you can make me laugh and love dogs!"],
  cmjrkgtpe0007dxgd8asbhu0g: [
    "Kindness and a good cup of coffee.",
    "A thoughtful message.",
    "A spontaneous road trip invitation.",
  ],
  cmjrkgtpe0008dxgd00g7i3l4: ["A meme that was actually funny!"],
  cmjrkgtpe0009dxgd267l0mni: [
    "I'm always up for an adventure.",
    "I love learning new things.",
    "I can't resist a good pizza.",
  ],
  cmjrkgtpe000adxgdc2damwt9: ["Reading a book with some tea."],
  cmjrkgtpe000bdxgdku6w12gs: [
    "Journaling every morning.",
    "Trying to meditate daily.",
    "Drinking more water.",
  ],
  cmjrkgtpe000cdxgdhn3lgz4u: ["Love-hate. Can't live without it, but try to!"],
  cmjrkgtpe000ddxgdsnj6migx: [
    "Building a shelter and finding food.",
    "Starting a fire and keeping spirits high.",
    "Organizing group activities.",
  ],
  cmjrkgtpe000edxgdkphyr1t9: ["Watching my favorite movie."],
  cmjrkgtpe000fdxgd86dcnc6e: ["Honesty.", "Loyalty.", "Kindness."],
  cmjrkgtpe000gdxgdkdnxolge: ["Empathy and a sense of humor."],
  cmjrkgtpe000hdxgd6rjsia3s: [
    "My supportive friends and family.",
    "Having a job I love.",
    "Good health.",
  ],
  cmjrkgtpe000idxgdy3bphhu9: ["Communication and trust."],
  cmjrkgtpe000jdxgd1oqgp95z: [
    "Being more patient.",
    "Improving my fitness.",
    "Learning to say no.",
  ],
};
